#!/bin/bash

## Install Tmux
sudo apt -y install tmux

## Install oh-my-zsh
sudo apt -y install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

## Install Python
sudo add-apt-repository ppa:deadsnakes/ppa -y
sudo apt -y install python3.12-full python3.12-venv python3-pip
pythom -m pip install requests

## Install NodeJS
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
\. "$HOME/.nvm/nvm.sh"
nvm install 22

## Install Luarocks
sudo apt -y install luarocks
luarocks install luacheck

## Install Rust and Cargo
curl https://sh.rustup.rs -sSf | sh -y

## Install Ansible and Terraform
sudo apt -y install terraform
pip3 install --upgrade --user ansible ansible-lint
ansible-galaxy collection install ansible.posix community.docker

## Install Neovim
sudo snap install nvim --classic
sudo apt -y install gcc make python3-neovim fzf ripgrep fd-find libssl-dev luajit

## Clean APT
sudo apt autoremove
